### ISSUE TITLE
peer dep missing

### ISSUE THREAD

**Issue by xduseko** [jscrambler/gulp-jscrambler#5] opened 2017-05-22 16:33 UTC
Module `gulp-jscrambler` depends on `jscrambler`, which depends on `grunt-contrib-clean`, which depends on `grunt`.
Command `npm shrinkwrap` fails when `grunt` is not installed. Who would want Grunt, when installing Gulp plug-in?

**Comment by magalhas** [comment] 2017-06-07 14:01
Checking [here](https://github.com/jscrambler/javascript-jscrambler/blob/master/package.json#L39) the problem is that `grunt-contrib-clean` is declared twice, as a dev and a normal dependency. It should be only a dev dependency so that this does not happen.

**Comment by CMatias** [comment] 2017-06-07 14:36
Fixed in our newest version (1.1.8).

**Comment by CodeMan99** [comment] 2017-07-10 14:27
This issue was fixed for jscrambler/javascript-jscrambler@f9266fec44b19a1aa438d17985e334fa6070b41d, but not this repository. gulp-jscrambler is depending on v1.1.2 off jscrambler.

**Comment by CMatias** [comment] 2017-07-10 14:35
True. Will fix.

**Comment by CodeMan99** [comment] 2017-07-10 14:37
Opened the pull request #7

**Comment by CodeMan99** [comment] 2017-11-21 05:50
@xduseko @magalhas @CMatias This issue seems like it is addressed by the recent releases.

**Comment by CMatias** [comment] 2017-11-21 18:07
We're currently updating all the packages (grunt, gulp, webpack) which depend on the main jscrambler package everytime the latter is updated. Thank you for helping us make Jscrambler better and apologies for the slow response.

**Closed by CMatias** 2017-11-21 18:07 UTC
